services:
  - type: web
    name: control-de-limpieza
    runtime: python
    buildCommand: python -m py_compile app.py
    startCommand: python app.py
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: REMINDER_EMAIL
        value: i.reymelloni@gmail.com
      - key: RESEND_FROM_EMAIL
        value: onboarding@resend.dev
