-- Ejecutar en Supabase > SQL Editor.
-- La app usa estas tablas cuando SUPABASE_URL y SUPABASE_SERVICE_ROLE_KEY están configuradas;
-- sin ellas mantiene el almacenamiento JSON local para desarrollo y pruebas.

create table if not exists public.tareas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  intervalo_dias integer not null check (intervalo_dias > 0),
  es_recurrente boolean not null default false,
  asignada_a text check (asignada_a in ('Montserrat', 'Iñaki')),
  ultima_realizacion timestamptz,
  realizada_por text check (realizada_por in ('Montserrat', 'Iñaki')),
  creada_en timestamptz not null default now()
);

create table if not exists public.subtareas (
  id bigint generated by default as identity primary key,
  tarea_id bigint not null references public.tareas(id) on delete cascade,
  nombre text not null,
  intervalo_dias integer not null check (intervalo_dias > 0),
  ultima_realizacion timestamptz,
  realizada_por text check (realizada_por in ('Montserrat', 'Iñaki')),
  creada_en timestamptz not null default now()
);

create index if not exists subtareas_tarea_id_idx
  on public.subtareas(tarea_id);

-- Historial inmutable de cada tarea o subtarea completada.
create table if not exists public.historial_tareas (
  id bigint generated by default as identity primary key,
  tarea_nombre text not null,
  subtarea_nombre text,
  completada_por text not null check (completada_por in ('Montserrat', 'Iñaki')),
  completada_en timestamptz not null default now()
);

create index if not exists historial_tareas_fecha_idx
  on public.historial_tareas(completada_en desc);

alter table public.tareas enable row level security;
alter table public.subtareas enable row level security;
alter table public.historial_tareas enable row level security;

-- El acceso seguirá protegido por la contraseña de la aplicación.
-- No se crean políticas públicas todavía: se definirán al conectar Supabase.
